### ISSUE TITLE
Could you share your bios version and settings?

### ISSUE THREAD

**Issue by josedotjs** [sveinar/opencore-asus-tuf-z490#3]
Hi, me again, sorry. I am stucked in the instalation process, the recovery finishes,  when reboot and init from the hard drive i get the message "Mac os could not be installed on your computer".
Can you share your bios version and the options changed from the optimal settings?

Thanks in advance.

**Comment by sveinar** [comment]
Thanks mate, I did follow and set these BIOS settings:
https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#intel-bios-settings

**Comment by josedotjs** [comment]
Hi, thanks for the response, i refer to the bios version of the Z490-PLUS  WIFI. I have the 1208 version, make the recomended changes, but the HDMI outputof the IGPU get the black screen after the initial boot  (my monitor is HDMI only) . With the RX 580 changing the boot arguments  can proceed with the instalation but i get an error   when the instalation is finishing. Maybe i am missing something in my bios config.
PS: The WIFI is working in your hack?

Thank you very much, sorry for my bad english

**Comment by sveinar** [comment]
Thank you. Yes, I am using the 1208 from the 10th August 2020 for my BIOS. I use the iGPU DP output in my setup and that works great. But I do suspect the instructions here might help perhaps for the HDMI https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md.

To the problem of not being able to install.
1) Could this be an issue with the SMBIOS ID that you are using? Did you use iMac20,1 ?
2) Have you tried with completing the installation using the iGPU instead and then deal with the RX 580 later on? There are boot options for both, disabling IGPU and disabling dedicated GPU...

**Comment by josedotjs** [comment]
Yes, im using  iMac20,1 whit the serials generated by macserial.exe in the opencore utilities, i will try making the changes for the HDMI output using the igpu.
Wich version of catalina are you using?

Thank you

**Comment by sveinar** [comment]
Thank you, good. 
10.15.7 of Catalina here.

Good luck mate!

**Comment by josedotjs** [comment]
Hi, the previous error was a generalizated problem with the Apple servers in my country (Argentina). I tried trough a vpn and works wonderfully. Only the wifi is missing (shows a second ethernet card). Thank you very much, great work.
